### ISSUE TITLE
Combat and Combat Tracker

### ISSUE THREAD

**Issue by dylanpiera** [pokemon-tabletop-reunited/ptr2e#4]
## Combat and Combat Tracker
- Combat Tracker using new Initiative System
- Different Combatant Types (regular, round, effect)

This issue is a pooling epic to track associated components of the work that would be scoped.

### Combat Functionality
- Action Advancement / Delay
- Speed Changes

### Combat UI
- [x] https://github.com/pokemon-tabletop-reunited/ptr2e/issues/35
- [ ] #201

### API Improvements
- [x] https://github.com/pokemon-tabletop-reunited/ptr2e/issues/33
- [x] https://github.com/pokemon-tabletop-reunited/ptr2e/issues/34
