### ISSUE TITLE
EPIC: Beta Tracker

### ISSUE THREAD

**Issue by dylanpiera** [pokemon-tabletop-reunited/ptr2e#580]
## Public Beta Tracker
This issue is to keep track of when we will be ready for Public Beta, and the OP should be edited with the latest updates.

## Require Technical Implementation
These issues require technical implementation to make the acompanied rules playable, either because the action is too complex, just plainly not possible, or too much of a PITA to do without (proper) automation.
- [x] #345 
- [x] #227
- [x] #546 
- [x] #536 
- [ ] Blueprint based Actor Generation
- [x] #484 
- [x] #333 
- [x] #264 
- [x] #67  
- [x] #34

## Require Rules Design
These issues require rules design & discussion and may or may not need foundry implementation post the design phase.
- [x] #574 
- [ ] Phenomena (Mega, Z-Moves, Dynamax, Tera)

## Require data entry
These issues require (complex) data entry, such as creating items or balancing the dex.
- [ ] Add all 'vanilla' Forme Change information once foundry support has been added
- [ ] Proper Gear (armor, equipment like scanners, multitools, flashlights, rafts, etc.)

## Nice-to-have Technical Implementation
These issues do not require technical implementation to be playable but would benefit (significantly) from more bespoke automation.
- [x] #577 
- [x] #555 
- [ ] Make prerequisites clearer on the Perk Web and attach automation to them (such as that the system knows if you have enough of a certain skill to allow you to pick a perk)
- [ ] Auto-Perk Assigner & Perk Suggestions based on Blueprint settings
- [x] #474 
- [x] #337 
- [x] #336 
- [x] #335 
- [x] #272 
- [x] #270 
- [x] #249 
- [x] #248 
- [x] #155 

## QOL
These issues are for QoL features that would be nice to have, but are not to be prioritized, and do not block the beta launch, but would be appreciated none-the-less.
- [x] #579 
- [x] #533 
- [x] #524 
- [x] #521 
- [ ] #505 
- [x] #493 
- [x] #489 
- [x] #357 
- [x] #346 
- [x] #265 
- [x] #251 
- [x] #170 
- [x] #169
- [ ] #17
- [ ] Bespoke automation for Tera (Tera type field on an Actor, and a button to Tera, changing type + adding the 'double' stab)

## Future Rule Design
These issues are for 'Expansion material', not mission critical for Beta, but something we do want to include in the final product
- [ ] Shadow Subsystem
